.TH HELLO-OLD "1"  "Sep 2010" "HELLO-OLD 0.1" "say hello"
.SH NAME
\fBhello-newbie \fP- say hello
.SH DESCRIPTION
hello-old is a program that says hello to users.
.SH HOW TO USE
Just type 'hello-old' at command prompt.
.SH SEE ALSO
\fBhello\fP(1).
.SH AUTHOR
Hello Old was written by Joao Eriberto Mota Filho <eriberto@eriberto.pro.br>.
